env:
  global:
    - SITL_SPEEDUP=10
    - SITL_RATE=200

python:
  - 2.7.13
  - 3.6

install:
  - 'pip install -r requirements.txt'
  - pip install flake8

before_script:
  # --exit-zero means that flake8 will not stop the build
  # 127 characters is the width of a GitHub editor
  # E703 statement ends with a semicolon
  # E711 comparison to None should be 'if cond is None:'
  # E712 comparison to False should be 'if cond is False:' or 'if not cond:'
  # E713 test for membership should be 'not in'
  # E999 SyntaxError: invalid syntax
  # F401 'socket' imported but unused
  # F403 'from dronekit import *' used; unable to detect undefined names
  # F811 redefinition of unused 'types' from line 45
  # F821 undefined name 'xrange'
  flake8 . --count --exit-zero --max-line-length=127 --select=E703,E711,E712,E713,E999,F401,F403,F811,F821 --statistics

script:
  - 'nosetests --debug=nose,nose.importer --debug-log=nose_debug -svx dronekit.test.unit'
  - 'nosetests --debug=nose,nose.importer --debug-log=nose_debug -svx dronekit.test.sitl'

git:
  depth: 10

language: python

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f3f81b74f930dac9583a
    on_success: change
    on_failure: always
    on_start: never

matrix:
  allow_failures:
  - python: 3.6
  fast_finish: true

branches:
  only:
    - master
